INDEXING AND SLICING

In [5]:

import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(a1[-1])
print(a1[5])

9
5


In [10]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
print(a2[1][3])

7


In [12]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
print(a3[1][0][1])

5


In [14]:
#slicing

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(a1[0:3])
print(a1[1:7:2])

[0 1 2]
[1 3 5]


In [16]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [19]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
