In [1]:
#CREATING A NUMPY ARRAY

import numpy as np

a = np.array([1,2,3,4,5])
print(a)


#type 

print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#2d and 3d 

b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
print(type(c))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [9]:
#forming an array of our own datatype
a=np.array([1,2,3,4,5], dtype=float)
print(a)
print(type(a))


[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [12]:
# np.arange

x=np.arange(1,11)
print(x)

#with a gap of 2 
y=np.arange(1,11,2)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [14]:
#np reshape 

np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [3]:
#random
import numpy as np
x=np.random.random((3,4))
print(x)

[[0.36056337 0.7611535  0.25356252 0.48827079]
 [0.71572743 0.65091053 0.38170828 0.24456922]
 [0.46675727 0.25325545 0.16382937 0.91558767]]


In [4]:
#np linspace or linearly space

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [6]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])