RESHAPING IN NUMPY

In [2]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
a3
print(a1.shape, a2.shape, a3.shape)

(10,) (3, 4) (2, 2, 2)


In [3]:
#transpose

print(np.transpose(a1))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(np.transpose(a2))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [5]:
print(np.transpose(a3))

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [6]:
#ravel converts any dimension of array into 1 dimension array

print(np.ravel(a2))



[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
print(np.ravel(a3))

[0 1 2 3 4 5 6 7]
