In [1]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [2]:
#horizontal stacking

print(np.hstack(a2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
print(np.vstack(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(np.vstack(a1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [5]:
print(np.vstack(a3))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [6]:
print(np.hstack(a2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
print(np.hstack(a2,a3))

TypeError: hstack() takes 1 positional argument but 2 were given